### ISSUE TITLE
Auto center client on spacebar shoudl be optional

### ISSUE THREAD

**Issue by bobifle** [JamzTheMan/MapTool#69] opened 2018-06-06 23:45 UTC
When the GM hit the spacebar to pop up an arrow visible to clients, the client auto center the view on the arrow. This is super annoying.

There should be a way to disable this feature.

**Comment by JamzTheMan** [comment] 2018-06-06 23:50
Duplicate of #63

**Closed by JamzTheMan** 2018-06-06 23:50 UTC
Labels: duplicate
