### ISSUE TITLE
Drag path does not seem to be working correctly.

### ISSUE THREAD

**Issue by leowalter** [JamzTheMan/MapTool#77] opened 2018-06-22 00:33 UTC
First image is from 1.4.4.2
https://i.imgur.com/29lsK1A.png

Send image is from 1.4.5.0
https://i.imgur.com/1Q1FAAC.png

With 1.4.5.0 I tried with AI on and off.

**Comment by JamzTheMan** [comment] 2018-06-22 01:01
It's the same "cost" but ya. Technically, with AI on or off it uses the same algorithm to plot a path, it just ignores vbl/terrain when AI is off.

I plan to take a optimization pass in a future release to get it to do prettier diagonals...

It's "working as designed" but will hopefully "correct" it in the near future.

**Comment by leowalter** [comment] 2018-06-22 01:04
OK. Thanks.  Will just continue using 1.4.4.2.  Too many years our group has used the blue line to determine path and resolve AoO.  Thanks for all the work you put into this!!!

**Comment by JamzTheMan** [comment] 2018-06-22 01:09
The "blue line" path is still valid. And "technically" this would be more accurate once you put VBL in (and terrain modifiers).  And if you want to walk in a more diagonal path vs up and over, you can move, right click, move, right click (to set way points).

But I get ya, it's not what you are use to.  I do hope you try it on a few maps with VBL first though before giving up on it. 😄

**Comment by JamzTheMan** [comment] 2018-06-22 01:35
Yep yep. but if there were npc's more in the middle, it would avoid those more in this example.  Whether you go 2 block up and 6 over or 1 up 3 over 1 up 3 over the math is the same, it's just not as 'pretty'.

I did try to get that back but just sort of ran out of time.  I will def note this and keep this open. You'll get a notification when this is "fixed" 😄 

FYI: Free tidbit, if you Edit Token -> Config Tab -> Terrain Modifier and put a value like, say 999 in them, the PC tokens will actually avoid walking through those tokens. (All depends if your game lets that happen or not of course. I know this doesn't "fix" this issue, just throwing it out there.

**Comment by leowalter** [comment] 2018-06-22 07:03
Awesome!  Thanks Jamz.

**Comment by JamzTheMan** [comment] 2018-06-22 19:29
_Notes to self..._

Marking as enhancement (as working as designed).
Info on working on tie-breaking algorithm: http://theory.stanford.edu/~amitp/GameProgramming/Heuristics.html#heuristics-for-grid-maps

There are several trade offs when handling tie breaking, article goes into this pretty well.

**Comment by JamzTheMan** [comment] 2018-06-23 03:33
It turned out not as hard as I thought, always good to take a step back and reexamine things. 😄 

This is fixed in 1.4.5.2,

**Closed by JamzTheMan** 2018-06-23 03:33 UTC
Labels: enhancement, fixed, in progress

**Comment by leowalter** [comment] 2018-06-23 16:11
Not the same as 1.4.4.2, but much better than 1.4.5.0 and very usable.  THANKS!!!!

**Comment by JamzTheMan** [comment] 2018-06-23 16:14
Yea, I couldn't get it 100% the same because the math is different and more complicated now. Thanks for keeping me honest lol  After taking a second look, it really did produce some "unnatural" results in open areas.
